# It's not worth creating a bunch of db schema info for this data which is only
# used to generate informational text.
# DO NOT let this yaml become a dumping ground for things that should be in
# the db (famous last words).  Rule of thumb: If you need to know the value
# behind the formatted text, don't put it here.

install_day: "Friday, July 5, 2019"
skill_attend_day: "Friday, June 28, 2019"
temple:
  contract_deadline: "Friday, February 22, 2019"
  schedule: ["Friday, February 22, 2019: Signed Contracts Due",
             "Tuesday, February 25, 2019: Check cut and sent",
             "Tuesday, July 2 - Sunday, July 7, 2019: Firefly!"]
moonshot:
  contract_deadline: "Friday, February 22, 2019"
  schedule: ["Friday, February 22, 2019: Signed Contracts Due",
             "Tuesday, February 25, 2019: Check cut and sent",
             "Tuesday, July 2 - Sunday, July 7, 2019: Firefly!",
             "Monday, July 22, 2019: Firefly documentation due"]
creativity:
  contract_deadline: "Friday, April 5, 2019"
  schedule: ["Friday, April 5, 2019: Signed Contracts Due",
             "Monday, April 8, 2019: First check cut and sent",
             "Tuesday, July 2 - Sunday, July 7, 2019: Firefly!",
             "Monday, July 22, 2019: Firefly documentation due",
             "Tuesday, July 30, 2019: Second check cut and sent"]
legacy:
  contract_deadline: "Friday, April 19, 2019"
  schedule: ["Friday, April 19, 2019: Signed Contracts Due",
             "Monday, April 22, 2019: Check cut and sent",
             "Tuesday, July 2 - Sunday, July 7, 2019: Firefly!"]
skillshare:
  contract_deadline: "Friday, April 19, 2019"
  schedule: ["Friday, April 19, 2019: Signed Contracts Due",
             "Monday, April 22, 2019: Check cut and sent",
             "Tuesday, July 2 - Sunday, July 7, 2019: Firefly!"]
bex:
  contract_deadline: "Friday, April 19, 2019"
  schedule: ["Friday, April 19, 2019: Signed Contracts Due",
             "Monday, April 22, 2019: Check cut and sent",
             "Tuesday, July 2 - Sunday, July 7, 2019: Firefly!"]
